services:

    # adapter: country
    I18nBundle\Adapter\Country\AbstractCountry:
        abstract: true
        public: false

    I18nBundle\Adapter\Country\System:
        parent: I18nBundle\Adapter\Country\AbstractCountry
        public: false
        tags:
            - { name: i18n.adapter.country, alias: system }

    I18nBundle\Adapter\Country\CoreShop:
        parent: I18nBundle\Adapter\Country\AbstractCountry
        public: false
        tags:
            - { name: i18n.adapter.country, alias: coreshop }

    # adapter: language
    I18nBundle\Adapter\Language\AbstractLanguage:
        abstract: true
        public: false

    I18nBundle\Adapter\Language\System:
        parent: I18nBundle\Adapter\Language\AbstractLanguage
        public: false
        tags:
            - { name: i18n.adapter.language, alias: system }

    # adapter: pathGenerator
    I18nBundle\Adapter\PathGenerator\AbstractPathGenerator:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\PathGenerator\StaticRoute:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        public: false
        tags:
            - { name: i18n.adapter.path.generator, alias: static_route }
        calls:
            - ['setUrlGenerator', ['@router']]
            - ['setRequest', ['@request_stack']]

    I18nBundle\Adapter\PathGenerator\Document:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        public: false
        tags:
            - { name: i18n.adapter.path.generator, alias: document }

    # adapter: context
    I18nBundle\Adapter\Context\AbstractContext:
        abstract: true
        public: false
        autowire: true

    I18nBundle\Adapter\Context\Country:
        parent: I18nBundle\Adapter\Context\AbstractContext
        public: false
        tags:
            - { name: i18n.adapter.context, alias: country }

    I18nBundle\Adapter\Context\Language:
        parent: I18nBundle\Adapter\Context\AbstractContext
        public: false
        tags:
            - { name: i18n.adapter.context, alias: language }
