services:

    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    I18nBundle\Helper\DocumentHelper: ~

    I18nBundle\Helper\CookieHelper: ~

    I18nBundle\Helper\UserHelper: ~