services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # manager: zone
    I18nBundle\Manager\ZoneManager: ~

    # manager: path_generator
    I18nBundle\Manager\PathGeneratorManager: ~

    # manager: context
    I18nBundle\Manager\ContextManager: ~