services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # registry: locale
    I18nBundle\Registry\LocaleRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Locale\LocaleInterface

    # registry: path generator
    I18nBundle\Registry\PathGeneratorRegistry:
        arguments:
            $interface: I18nBundle\Adapter\PathGenerator\PathGeneratorInterface

    # registry: context
    I18nBundle\Registry\ContextRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Context\ContextInterface

    # registry: redirector
    I18nBundle\Registry\RedirectorRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Redirector\RedirectorInterface