services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # registry: language
    I18nBundle\Registry\LanguageRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Language\LanguageInterface

    # registry: country
    I18nBundle\Registry\CountryRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Country\CountryInterface

    # registry: path generator
    I18nBundle\Registry\PathGeneratorRegistry:
        arguments:
            $interface: I18nBundle\Adapter\PathGenerator\PathGeneratorInterface

    # registry: context
    I18nBundle\Registry\ContextRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Context\ContextInterface