services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # tool: installer
    I18nBundle\Tool\Install:
        public: true

    # configuration
    I18nBundle\Configuration\Configuration: ~

    # session: configurator
    I18nBundle\Session\SessionConfigurator:
        tags:
            - { name: pimcore.session.configurator }