services:

    # tool installer
    i18n.tool.installer:
        class: I18nBundle\Tool\Install
        arguments: ['@logger']
        tags:
            - { name: monolog.logger }

    # session configurator
    i18n.session.configurator:
        class: I18nBundle\Session\SessionConfigurator
        tags:
            - { name: pimcore.session.configurator }

    # helper
    i18n.document.relation_helper:
        class: I18nBundle\Document\Helper\DocumentRelationHelper
        public: false

    # helper
    i18n.user.guesser:
        class: I18nBundle\User\I18nGuesser
        arguments: ['@i18n.configuration']
        public: false

    # configuration
    i18n.configuration:
        class: I18nBundle\Configuration\Configuration
        arguments: ['@i18n.country_adapter']

    # check if current path is in right (hard link) context
    i18n.pathfinder:
        class: I18nBundle\Pathfinder\Pathfinder
        arguments: ['@request_stack', '@pimcore.locale']
        public: false

    I18nBundle\PathResolver\Path\AbstractPath:
        abstract:  true
        arguments: ['@router', '@i18n.configuration', '@i18n.document.relation_helper']

    i18n.path.resolver.static_route:
        parent: I18nBundle\PathResolver\Path\AbstractPath
        class: I18nBundle\PathResolver\Path\StaticRoutePath
        calls:
            - ['setMasterRequest', ['@=service("request_stack").getMasterRequest()']]

    i18n.path.resolver.document:
        parent: I18nBundle\PathResolver\Path\AbstractPath
        class: I18nBundle\PathResolver\Path\DocumentPath

    i18n.path.resolver:
        class: I18nBundle\PathResolver\PathResolver
        arguments: ['@request_stack', '@i18n.path.resolver.static_route', '@i18n.path.resolver.document']

    I18nBundle\ContextResolver\ContextFactory: ~
    i18n.context.resolver:
        factory: 'I18nBundle\ContextResolver\ContextFactory:get'
        class: I18nBundle\ContextResolver\ContextResolver
        arguments: ['%i18n.mode%']
        calls:
            - [setCurrentContext, ['%i18n.mode%']]
            - [setConfiguration, ['@i18n.configuration']]
            - [setPathResolver, ['@i18n.path.resolver']]
            - [setRelationHelper, ['@i18n.document.relation_helper']]
            - [setGuesser, ['@i18n.user.guesser']]

    # country adapter
    i18n.country.adapter.flat:
        class: I18nBundle\Country\Adapter\Flat
    i18n.country.adapter.website:
        class: I18nBundle\Country\Adapter\Website
    i18n.country.adapter.coreshop:
        class: I18nBundle\Country\Adapter\CoreShop

    # i18n detector, register language / country. redirect user
    i18n.event_listener.detector:
        class: I18nBundle\EventListener\DetectorListener
        arguments: ['@i18n.configuration', '@pimcore.service.request.document_resolver', '@i18n.document.relation_helper', '@i18n.user.guesser']
        calls:
            - [setPimcoreContextResolver, ['@pimcore.service.request.pimcore_context_resolver']]
        tags:
            - { name: kernel.event_subscriber }

    # check frontend path
    i18n.event_listener.frontend.path.document:
        class: I18nBundle\EventListener\Frontend\FrontendPathListener
        arguments: ['@i18n.pathfinder']
        tags:
            - { name: kernel.event_subscriber }

    # check link paths (correct link path when redirection in hardlink context)
    i18n.event_listener.link_path_resolver:
        class: I18nBundle\EventListener\Frontend\LinkPathListener
        arguments: ['@pimcore.service.request.document_resolver', '@i18n.pathfinder']
        calls:
            - [setPimcoreContextResolver, ['@pimcore.service.request.pimcore_context_resolver']]
        tags:
            - { name: kernel.event_subscriber }

    # removes canonical Link tag from hardlink headers
    i18n.event_listener.frontend.canonical:
        class: I18nBundle\EventListener\CanonicalListener
        arguments: ['@pimcore.service.request.document_resolver']
        tags:
            - { name: kernel.event_subscriber }

    # adds i18n meta tags to HeadMeta view helper
    i18n.event_listener.frontend.document_head_meta:
        class: I18nBundle\EventListener\Frontend\HeadMetaListener
        arguments: ['@pimcore.service.request.document_resolver', '@pimcore.templating.view_helper.head_meta', '@i18n.context.resolver']
        tags:
          - { name: kernel.event_subscriber }

    # adds i18n meta tags to HeadMeta view helper
    i18n.event_listener.frontend.document_head_link:
        class: I18nBundle\EventListener\Frontend\HeadLinkListener
        arguments: ['@pimcore.service.request.document_resolver', '@pimcore.templating.view_helper.head_link', '@i18n.context.resolver']
        tags:
          - { name: kernel.event_subscriber }