services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\DataCollector\I18nDataCollector:
        tags:
            -
                name:     data_collector
                template: 'I18nBundle:Profiler:data_collector.html.twig'
                id:       'i18n.data_collector'
                priority: 500